name: ConanSMP
version: '${project.version}'
main: me.chaounne.conansmp.ConanSMP
api-version: 1.19
description: Conan SMP Plugin
author: Chaounne
commands:
  coords:
    description: Send your coordinates
    usage: /coords
    aliases: coords
  duel:
    description: Duel a player to a CCG match
    usage: /duel <player>
    aliases: duel
  inv:
    description: Open the commmon inventory
    usage: /inv
    aliases: inv
